Lra 434 avm create a source selection for the source input button
lsa-mis/avmonitor pull request #39
Opened 2022-10-28 22:18 UTC by britaumich

This is a draft pull request. 
On a room show page a drop down menu of available sources is displayed for a projector. If a source is changed the sendtosocket stimulus controller will fetch /send_to_room/${room_id}?operation=source_int&source=${source_id}` to send a message to the socket.
For testing I commented SendSocketJob in the send_to_room method.
Instead of starting that job I added Rails.logger command to print msg in the rails log.

2022-11-08 17:00 UTC, britaumich commented
@rsmoke The last commit sends the correct value as a selected source to the websocket.
I can uncomment SendSocketJob in the rooms_controller and convert the PR from draft to active one or do you have any other comments before I do that?

2022-11-09 23:06 UTC, britaumich commented
I merged LRA-433-avm-create-a-toggle-for-volume-level-from-1-100 into this branch because they both use the same stimulus controller and the same method in rooms_controller, and create things on the same room show page.
I uncommented   SendSocketJob in the send_to_room method.

2022-11-14 16:06 UTC, rsmoke requested changes
change the setting of the hardcoded value for the asset 'Projector 1' to be dynamic. See inline comment

2022-11-14 16:06 UTC, rsmoke commented on app/controllers/rooms_controller.rb
>        msg = "{'LSARoom': {'Assets':{'Projector 1':{'BooleanOutputs': {'Power On': true}}}, 'Password': 'LSAPassword'}}"
Initially the JSON being sent for the "projector_on" and "projector_off" were hard coded to the asset name of 'Projector X". This needs to be dynamic now. @britaumich and @rsmoke discussed @britaumich  adding the change to making this dynamic. This also is on line 145

2022-11-21 21:13 UTC, closed without merging