Lra 373 broadcast attention message to header
lsa-mis/avmonitor pull request #6
Opened 2022-07-14 21:07 UTC by britaumich

Broadcast "Attention Needed" messages

- attention model created to create "Attention needed" or "" message to broadcast it from the model
- attention_channel.js updates a Dashboard
- lib/tasks/check_rooms_status.rake - a task that checks states and broadcasts "attention needed" or clear message

Lamp Hours filter

- index.html.erb displays a filter
- rooms_comtroler - creates @rooms
- autosubmit_controller.js - validated input values
- config/initializers/constants.rb - min and max numbers for lamp hours 

_room_card has updated information about rooms

Please let me know if you have questions

2022-07-14 22:09 UTC, rsmoke requested changes
delete commented or unused code. 
This is certainly a big step and a major improvement. I would like to walk through the PR with  you.

2022-07-14 22:09 UTC, rsmoke commented on lib/tasks/check_rooms_status.rake
> +task check_rooms_status: :environment do
When does this rake task get called?

2022-07-14 22:09 UTC, rsmoke commented on lib/tasks/check_rooms_status.rake
> +desc "This will find rooms that need attention"
when or what triggers this task

2022-07-14 22:20 UTC, britaumich commented on lib/tasks/check_rooms_status.rake
> +task check_rooms_status: :environment do
It's called from the cron job:
```
litx-brita:avmonitor brita$ crontab -l
*/1 * * * * /bin/bash -l -c 'export PATH="/Users/brita/.rbenv/bin:$PATH"; eval "$(rbenv init -)"; cd /Users/brita/avmonitor && RAILS_ENV=development bundle exec ./bin/rake check_rooms_status' >> /Users/brita/cron_logs/cron.txt 2>&1
```

2022-07-14 22:25 UTC, britaumich commented on app/views/attentions/_attention.html.erb
> +<span>
oh no, my usual error again - fixed

2022-07-14 22:26 UTC, britaumich commented on app/javascript/controllers/autosubmit_controller.js
> +      // if (min_lamp_hour != 0 && min_lamp_hour > MIN || max_lamp_hour != 0 && max_lamp_hour < MAX) {
done

2022-07-14 22:27 UTC, britaumich commented on lib/tasks/check_rooms_status.rake
> +desc "This will find rooms that need attention"
t's called from the cron job:
```
litx-brita:avmonitor brita$ crontab -l
*/1 * * * * /bin/bash -l -c 'export PATH="/Users/brita/.rbenv/bin:$PATH"; eval "$(rbenv init -)"; cd /Users/brita/avmonitor && RAILS_ENV=development bundle exec ./bin/rake check_rooms_status' >> /Users/brita/cron_logs/cron.txt 2>&1
```

2022-07-14 22:29 UTC, britaumich commented
> delete commented or unused code. This is certainly a big step and a major improvement. I would like to walk through the PR with you.

With pleasure - I'll review the code with you as soon as you have time for that.

2022-07-14 22:31 UTC, rsmoke requested changes

2022-07-14 22:31 UTC, rsmoke commented on app/views/attentions/_attention.html.erb
> +<span>
I am not seeing the fix here

2022-07-14 22:31 UTC, rsmoke commented on lib/tasks/check_rooms_status.rake
> +desc "This will find rooms that need attention"
can you add a comment in the code that describes the cron job. you set on your machine. IE. the output of the contab -l

2022-07-14 22:40 UTC, britaumich commented
> can you add a comment in the code that describes the cron job. you set on your machine. IE. the output of the contab -l

Too many comments. Here it is again:
It's called from the cron job:
```
litx-brita:avmonitor brita$ crontab -l
*/1 * * * * /bin/bash -l -c 'export PATH="/Users/brita/.rbenv/bin:$PATH"; eval "$(rbenv init -)"; cd /Users/brita/avmonitor && RAILS_ENV=development bundle exec ./bin/rake check_rooms_status' >> /Users/brita/cron_logs/cron.txt 2>&1
```

2022-07-14 22:41 UTC, britaumich commented on lib/tasks/check_rooms_status.rake
> +desc "This will find rooms that need attention"
```
litx-brita:avmonitor brita$ crontab -l
*/1 * * * * /bin/bash -l -c 'export PATH="/Users/brita/.rbenv/bin:$PATH"; eval "$(rbenv init -)"; cd /Users/brita/avmonitor && RAILS_ENV=development bundle exec ./bin/rake check_rooms_status' >> /Users/brita/cron_logs/cron.txt 2>&1
```

2022-07-14 22:47 UTC, rsmoke reviewed
Monday we will walk through this PR. Using ActionCable is cool stuff

2022-07-18 13:56 UTC, rsmoke reviewed
Need to √ for If not Attention message in system in RAKE task

2022-07-18 14:53 UTC, rsmoke approved these changes

2022-07-18 14:53 UTC, merged